### ISSUE TITLE
Ripser version?

### ISSUE THREAD

**Issue by hyang336** [FieteLab/SPUD_Analysis-of-manifold-structure-in-head-direction-data#1]
Hi, 

Could you let me know which Ripser version you used, they are only supporting Python 3.6 and above now. 

Thanks,
HY

**Comment by jd730** [comment]
Hi,
I just moved the codebase from our lab [webpage](https://fietelab.mit.edu/code/) to GitHub. Could you ask the first author of the paper, i.e., [Rishidev Chaudhuri](https://chaudhurilab.faculty.ucdavis.edu/people/)?

Thank you!
